import {it,expect,vi} from 'vitest';
const observed=vi.hoisted(()=>({child:null}));
vi.mock('node:child_process',async original=>{const actual=await original();return {...actual,fork:(...args)=>{observed.child=actual.fork(...args);return observed.child;}};});
import sharp from 'sharp';
import {mkdtemp,writeFile,readdir,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
const api=await import('../dist/images/prepare.js').catch(()=>({}));
async function fixture(width=1600,height=800,format='png',alpha=false){const root=await mkdtemp(join(tmpdir(),'image-prepare-'));const sourcePath=join(root,'input');await sharp({create:{width,height,channels:alpha?4:3,background:{r:20,g:60,b:140,alpha:alpha?0.5:1}}}).toFormat(format).toFile(sourcePath);return {sourcePath,outputDirectory:join(root,'prepared'),widthPt:144,heightPt:144};}
it('prepares a real smaller PNG at 200 DPI without changing aspect ratio or alpha',async()=>{expect(api.prepareImage).toBeTypeOf('function');const input=await fixture(1600,800,'png',true),r=await api.prepareImage(input);expect(r.status).toBe('prepared');expect(r.image).toMatchObject({width:400,height:200,mediaType:'image/png'});const m=await sharp(r.image.path).metadata();expect(m.width).toBe(400);expect(m.hasAlpha).toBe(true);const pixel=await sharp(r.image.path).raw().toBuffer();expect(pixel[3]).toBeGreaterThan(120);expect(pixel[3]).toBeLessThan(135);});
it('keeps small originals and reports their effective density',async()=>{const r=await api.prepareImage(await fixture(100,50));expect(r.image).toMatchObject({width:100,height:50});expect(r.warnings).toContainEqual(expect.objectContaining({code:'IMAGE_LOW_RESOLUTION'}));});
it('rotates EXIF JPEG before fitting portrait content and strips metadata',async()=>{const input=await fixture();await sharp({create:{width:1200,height:600,channels:3,background:'red'}}).jpeg().withMetadata({orientation:6}).toFile(input.sourcePath);const r=await api.prepareImage(input);expect(r.image).toMatchObject({width:200,height:400,mediaType:'image/jpeg'});const m=await sharp(r.image.path).metadata();expect(m.orientation).toBeUndefined();expect(m.exif).toBeUndefined();});
it('skips corrupt and unsupported files without publishing output',async()=>{for(const bytes of [Buffer.from('broken'),await sharp({create:{width:10,height:10,channels:3,background:'red'}}).webp().toBuffer()]){const input=await fixture();await writeFile(input.sourcePath,bytes);const r=await api.prepareImage(input);expect(r.status).toBe('skipped');expect(await readdir(input.outputDirectory)).toEqual([]);}});
it('rejects invalid geometry before decoding',async()=>{await expect(api.prepareImage({...await fixture(),widthPt:0})).rejects.toThrow();});
it('bounds input pixel count using decoder metadata',async()=>{const input=await fixture(6500,6500);const r=await api.prepareImage(input);expect(r.status).toBe('skipped');expect(await readdir(input.outputDirectory)).toEqual([]);});
it('timeout and cancellation kill child work and remove partial output',async()=>{const input=await fixture();const r=await api.prepareImage({...input,timeoutMs:1});expect(r.status).toBe('skipped');expect(r.warnings[0].code).toBe('IMAGE_TIMEOUT');expect(await readdir(input.outputDirectory)).toEqual([]);const abort=new AbortController();abort.abort();await expect(api.prepareImage({...input,signal:abort.signal})).rejects.toThrow();});
it('serializes decoder admission and cancels an active child before releasing it',async()=>{const input=await fixture(),abort=new AbortController();observed.child=null;const pending=api.prepareImage({...input,signal:abort.signal});const rejected=expect(pending).rejects.toThrow('cancelled');await expect(api.prepareImage(input)).rejects.toThrow('busy');for(let n=0;n<100&&!observed.child;n++)await new Promise(r=>setTimeout(r,5));expect(observed.child?.pid).toBeTypeOf('number');abort.abort();await rejected;expect(observed.child.exitCode!==null||observed.child.signalCode!==null).toBe(true);expect(await readdir(input.outputDirectory)).toEqual([]);expect((await api.prepareImage(input)).status).toBe('prepared');});
it('reports the prepared image density rather than the original density',async()=>{const r=await api.prepareImage(await fixture());expect(r.image.effectiveDpi).toBe(200);});
