import {it,expect} from 'vitest';
import {readFile,readdir} from 'node:fs/promises';
import {createHash,randomUUID} from 'node:crypto';
import {isolatedDatabase} from './isolatedDatabase.mjs';
import {migrate} from '../dist/db/migrate.js';
it('upgrades populated schema009 preserving IDs and constrains distinct band owners',async()=>{const db=isolatedDatabase();await db.setup();try{await db.pool.query('CREATE TABLE schema_migrations(name text PRIMARY KEY,checksum text NOT NULL,applied_at timestamptz NOT NULL DEFAULT now())');for(const name of (await readdir('migrations')).filter(n=>/^00[1-9]_.*sql$/.test(n)).sort()){const sql=await readFile('migrations/'+name,'utf8');await db.pool.query(sql);await db.pool.query('INSERT INTO schema_migrations(name,checksum) VALUES($1,$2)',[name,createHash('sha256').update(sql).digest('hex')]);}
 const tid='legacy',sid=randomUUID();await db.pool.query("INSERT INTO templates(id,doc_key,name) VALUES($1,$1,$1)",[tid]);await db.pool.query("INSERT INTO template_current(template_id,payload) VALUES($1,'{}')",[tid]);await db.pool.query('INSERT INTO variable_schemas(id,template_id,format_id) VALUES($1,$2,NULL)',[sid,tid]);
 const vid=randomUUID(),vsid=randomUUID();await db.pool.query("INSERT INTO template_versions(id,template_id,version,definition_json,fingerprint) VALUES($1,$2,1,jsonb_build_object('templateId',$2::text,'docKey',$2::text,'version',1),$3)",[vid,tid,'a'.repeat(64)]);await db.pool.query("INSERT INTO template_snapshots(version_id,payload) VALUES($1,'{}')",[vid]);await db.pool.query('INSERT INTO variable_schema_versions(id,template_version_id,format_version_id) VALUES($1,$2,NULL)',[vsid,vid]);
 const r=await migrate(db.pool);expect(r.ok,JSON.stringify(r)).toBe(true);expect((await db.pool.query('SELECT id,scope FROM variable_schemas WHERE id=$1',[sid])).rows).toEqual([{id:sid,scope:'global'}]);
 await db.pool.query("INSERT INTO variable_schemas(id,template_id,format_id,scope) VALUES($1,$2,NULL,'header')",[randomUUID(),tid]);await expect(db.pool.query("INSERT INTO variable_schemas(id,template_id,format_id,scope) VALUES($1,$2,NULL,'header')",[randomUUID(),tid])).rejects.toBeDefined();await expect(db.pool.query("INSERT INTO variable_schemas(id,template_id,format_id,scope) VALUES($1,$2,NULL,'format')",[randomUUID(),tid])).rejects.toBeDefined();
 expect((await db.pool.query('SELECT id,scope FROM variable_schema_versions WHERE id=$1',[vsid])).rows).toEqual([{id:vsid,scope:'global'}]);await expect(db.pool.query("UPDATE variable_schema_versions SET scope='header' WHERE id=$1",[vsid])).rejects.toBeDefined();expect((await migrate(db.pool)).ok).toBe(true);
 }finally{await db.close();}},30000);
